services:
  web:
    build:
      context: ../web/T02
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html:delegated
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
